services:
  - type: web
    name: webfeature
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
